### ISSUE TITLE
Fails to parse GitHub schema

### ISSUE THREAD

**Issue by hoijui** [oxidecomputer/progenitor#1028]
<https://github.com/github/rest-api-description/raw/refs/heads/main/descriptions/api.github.com/api.github.com.json>

> thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/progenitor-impl-0.9.0/src/method.rs:2023:23:
  not yet implemented: more media types than expected for markdown/render-raw: 2

**Comment by 2bndy5** [comment]
I removed the unsupported content type from the spec:
```json
            "text/x-markdown": {
              "schema": {
                "type": "string"
              },
              "examples": {
                "default": {
                  "summary": "Rendering markdown",
                  "value": {
                    "text": "Hello **world**"
                  }
                }
              }
            }
```
But now it fails to generate with a less helpful error:
```
  process didn't exit successfully: `/path/to/target/debug/build/github-client-9a409abff822b299/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=api.github.com.json

  --- stderr
  thread 'main' panicked at native/github-client/build.rs:8:51:
  called `Result::unwrap()` on an `Err` value: TypeError(InvalidValue)
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/std/src/panicking.rs:665:5
     1: core::panicking::panic_fmt
               at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/core/src/panicking.rs:76:14
     2: core::result::unwrap_failed
               at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/core/src/result.rs:1699:5
     3: build_script_build::main
     4: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
