### ISSUE TITLE
Panic while generating Up OpenAPI client

### ISSUE THREAD

**Issue by opeik** [oxidecomputer/progenitor#693]
Hi there!

I tried to generate a client for the [Up OpenAPI spec](https://github.com/up-banking/api/blob/master/v1/openapi.json) which seems to panic:

```
❯ RUST_BACKTRACE=1 cargo progenitor --input ynab_openapi_spec.yaml --output ynab --name ynab --v
ersion 0.1.0
thread 'main' panicked at /Users/opeik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/progenitor-impl-0.4.1/src/method.rs:1201:9:
assertion failed: response_types.len() <= 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a2d9d73e608f1b24eba840c4fd2d68dbe3b65e01/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/a2d9d73e608f1b24eba840c4fd2d68dbe3b65e01/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/a2d9d73e608f1b24eba840c4fd2d68dbe3b65e01/library/core/src/panicking.rs:144:5
   3: progenitor_impl::method::<impl progenitor_impl::Generator>::extract_responses
   4: progenitor_impl::method::<impl progenitor_impl::Generator>::method_sig_body
   5: progenitor_impl::method::<impl progenitor_impl::Generator>::positional_method
   6: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   7: core::iter::adapters::try_process
   8: progenitor_impl::Generator::generate_tokens
   9: cargo_progenitor::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ahl** [comment]
The part of the spec it's barfing on is here:

```yaml
      responses:
        "200":
          description: The requested category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryResponse"
        "404":
          description: The category not was found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          description: An error occurred
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
```

In short, this says, "200s will return a CategoryResponse; 404s will return ErrorResponse; and everything else will return ErrorResponse". Where we get hung up is that "everything else". If that's inclusive of success responses (say, a 201 or 202) should we expect to get `ErrorResponse`s for success codes as well? See https://github.com/OAI/OpenAPI-Specification/issues/3396

Given the ambiguity here and this common practice, I think we may want to change the interpretation to conform to the common law use of OpenAPI rather than its by-the-letter writing. So something like:

> default covers responses cases whose category is not otherwise mentioned

**Comment by ahl** [comment]
See #344
